/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.client.consultation.api;

import com.bytatech.ayoos.client.consultation.model.ConsultationDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-05-16T08:48:40.336+05:30[Asia/Kolkata]")

@Api(value = "ConsultationResource", description = "the ConsultationResource API")
public interface ConsultationResourceApi {

    @ApiOperation(value = "createConsultation", nickname = "createConsultationUsingPOST", notes = "", response = ConsultationDTO.class, tags={ "consultation-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConsultationDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/consultations",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<ConsultationDTO> createConsultationUsingPOST(@ApiParam(value = "consultationDTO" ,required=true )  @Valid @RequestBody ConsultationDTO consultationDTO);


    @ApiOperation(value = "deleteConsultation", nickname = "deleteConsultationUsingDELETE", notes = "", tags={ "consultation-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/consultations/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteConsultationUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllConsultations", nickname = "getAllConsultationsUsingGET", notes = "", response = ConsultationDTO.class, responseContainer = "List", tags={ "consultation-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConsultationDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/consultations",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ConsultationDTO>> getAllConsultationsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getConsultation", nickname = "getConsultationUsingGET", notes = "", response = ConsultationDTO.class, tags={ "consultation-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConsultationDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/consultations/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<ConsultationDTO> getConsultationUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchConsultations", nickname = "searchConsultationsUsingGET", notes = "", response = ConsultationDTO.class, responseContainer = "List", tags={ "consultation-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConsultationDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/consultations",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ConsultationDTO>> searchConsultationsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateConsultation", nickname = "updateConsultationUsingPUT", notes = "", response = ConsultationDTO.class, tags={ "consultation-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConsultationDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/consultations",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<ConsultationDTO> updateConsultationUsingPUT(@ApiParam(value = "consultationDTO" ,required=true )  @Valid @RequestBody ConsultationDTO consultationDTO);

}
