/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.client.doctor.api;

import com.bytatech.ayoos.client.doctor.model.DoctorDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-04-25T12:28:19.615+05:30[Asia/Calcutta]")

@Api(value = "CommandResource", description = "the CommandResource API")
public interface CommandResourceApi {

    @ApiOperation(value = "createDoctor", nickname = "createDoctorUsingPOST", notes = "", response = DoctorDTO.class, tags={ "command-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DoctorDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/commands/doctors",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<DoctorDTO> createDoctorUsingPOST(@ApiParam(value = "doctorDTO" ,required=true )  @Valid @RequestBody DoctorDTO doctorDTO);


    @ApiOperation(value = "test", nickname = "testUsingPOST", notes = "", response = String.class, tags={ "command-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/commands/doc",
        produces = "*/*", 
        method = RequestMethod.POST)
    ResponseEntity<String> testUsingPOST();


    @ApiOperation(value = "updateDoctor", nickname = "updateDoctorUsingPUT", notes = "", tags={ "command-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/commands/doctors",
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateDoctorUsingPUT(@ApiParam(value = "doctorDTO" ,required=true )  @Valid @RequestBody DoctorDTO doctorDTO);

}
